repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [ "--maxkb=1492" ]
      - id: no-commit-to-branch
        args: [ '--branch', 'main' ]

  - repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.10.5
    hooks:
      - id: typos
        exclude: >
          (?x)^(
              .*\.css|
              .*\.js|
              \.tox|
              tests/test_sample_ui/qml/icons.py
          )$


  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.0
    hooks:
      - id: poetry-check


  - repo: https://github.com/nrbnlulu/qt-hooks
    rev: v0.1.5
    hooks:
      - id: qml-format


  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
      - id: clang-format
        types:
          - c++
